version: "3.7"

services:
  echo:
    image: jwt-http-proxy:1
    build:
      context: .
    entrypoint:
      - /usr/local/bin/python
      - /app/echo_server.py
    environment:
      # Listening port
      ECHO_HTTP_PORT: "${ECHO_HTTP_PORT:-9200}"
    ports:
      - "${ECHO_HTTP_PORT:-9200}:${ECHO_HTTP_PORT:-9200}"
  proxy:
    image: jwt-http-proxy:1
    build:
      context: .
    entrypoint:
      - /usr/local/bin/python
      - /app/proxy_server.py
    environment:
      # Listening port, can be overridden
      PROXY_HTTP_PORT: ${PROXY_HTTP_PORT:-9100}
      # Upstream server, as server[:port], can also include a protocol as https://example.com
      UPSTREAM_SERVER: "echo:${ECHO_HTTP_PORT:-9200}"
      # Signing secret
      JWT_SIGNING_SECRET: a9ddbcaba8c0ac1a0a812dc0c2f08514b23f2db0a68343cb8199ebb38a6d91e4ebfb378e22ad39c2d01d0b4ec9c34aa91056862ddace3fbbd6852ee60c36acbf
    ports:
      - "${PROXY_HTTP_PORT:-9100}:${PROXY_HTTP_PORT:-9100}"
